version: '3.3'

services:
  app:
    image: graphqlapp
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/configs/config.yml
    volumes:
      - ./configs:/configs
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: post_comments
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
