// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string     `json:"id"`
	Content   string     `json:"content"`
	Author    *User      `json:"author"`
	Post      *Post      `json:"post"`
	Parent    *Comment   `json:"parent,omitempty"`
	Children  []*Comment `json:"children"`
	CreatedAt string     `json:"createdAt"`
}

type CommentPage struct {
	Comments []*Comment `json:"comments"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type Mutation struct {
}

type PageInfo struct {
	CurrentPage   int `json:"currentPage"`
	TotalPages    int `json:"totalPages"`
	TotalComments int `json:"totalComments"`
}

type Post struct {
	ID              string     `json:"id"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	Author          *User      `json:"author"`
	Comments        []*Comment `json:"comments"`
	CommentsEnabled bool       `json:"commentsEnabled"`
	CreatedAt       string     `json:"createdAt"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID       string     `json:"id"`
	Username string     `json:"username"`
	Email    string     `json:"email"`
	Posts    []*Post    `json:"posts"`
	Comments []*Comment `json:"comments"`
}
